Corp\EiisBundle\Entity\EiisUpdateNotification:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    uniqueConstraints:
        uniq_index1:
            columns: [ systemObjectCode, signalFrom ]
    fields:
        dateCreated:
            type: datetime
        systemObjectCode:
            type: string
            length: 255
        signalFrom:
            type: integer
    lifecycleCallbacks: {  }
